FROM quay.io/$USERNAME/output.builder:latest as builder
ARG EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2

USER 0
WORKDIR /workdir

RUN python3.11 generate_embeddings_tool.py -i /markdown -emd embeddings_model \
    -emn ${EMBEDDING_MODEL} -o vector_db -id vector_db_index

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
COPY --from=builder /workdir/vector_db /rag/vector_db
