FROM registry.access.redhat.com/ubi9/python-311
RUN cd /home
RUN mkdir rag 
COPY . /home/rag/
RUN mkdir -p lightspeed/data
RUN mkdir -p lightspeed/output 
WORKDIR /home/rag

RUN pip install -r requirements.txt